config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  
  devise_for :users , controllers: {
        registrations: 'users/registrations', 
        omniauth_callbacks: "users/omniauth_callbacks"

      }
  resources :profiles do
     resources :tweets
  end

  get '/feed' => 'feed#userfeed'
  root 'feed#userfeed'

  post "/follow/:profile_id/f" => "follows#create"
  post "/follow/:profile_id/u" => "follows#destroy"

  get "/search/:phrase" => "profiles#search"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


	def index
		#@q = Profile.ransack(params[:q])
		@prof = Profile.ransack(params[:q])
        @profiles = @prof.result(distinct: true)

        @prof2 = User.ransack(params[:q])
        @profiles2 = []
        @prof2.result(distinct: true).each do |user|
        	@profiles2 << user.profile.name
        end
        if @profiles2.length < User.all.count
        	@which = true
        else
        	@which = false
        end

	end

	def search
		 @prof = User.ransack(username_start: params[:phrase])
         @profiles = @prof.result(distinct: true)
         @str = ""
         @profiles.each do |profile|
          @str += profile.username+ ", "
         end
         @str = @str[0..@str.length-3]
         render "return"
         
	end


	def show
		@profile = Profile.find(params[:id])
		@tweets = @profile.user.tweets

	end

	def new
		@profile = Profile.new
	end

	def create
		paramsToSave = profile_params
		paramsToSave[:user] = current_user
		@profile = Profile.new(paramsToSave)
		if @profile.save
			redirect_to feed_path
		else
			render "new"
		end


	end

	private
	def profile_params
		params.require(:profile).permit(:name, :description)
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile.html.erb
<%=profile.name %> <%= auto_link_usernames("@"+profile.user.username) %> <br>

app/views/profiles/index.html.erb
<%= search_form_for @prof do |f| %>

  <%= f.label "Search by display name" %><br>
  <%= f.search_field :name_cont %><br>

  <%= f.submit %><br><br>
  
  <% end %>
  <%= search_form_for @prof2, url: "/profiles" do |f| %>

  <%= f.label "Search by username" %><br>
  <%= f.search_field :username_cont %><br>

  <%= f.submit %><br><br>

<% end %>

<h2>Results:</h2>

<% if @profiles.count==0 &&  @profiles2.count ==0%>
<h3>No results</h3>
<% end %>

<% if !@which %>
<% if @profiles.count==0%>
<h3>No results</h3>
<% end %>
<%= render @profiles %>
<% else %>
<% if @profiles2.count ==0%>
<h3>No results</h3>
<% end %>
<% @profiles2.each do |name|%>
 <%=name%> <%= auto_link_usernames("@"+Profile.where(name: name).first.user.username) %>
<% end %>
<% end %>

app/views/profiles/new.html.erb
<%= simple_form_for @profile do |f| %>

<%= f.input :name, label: "Enter a display name"%><br>
<%= f.input :description , label: "Enter a description"%><br>
<%= f.button :submit %>

<% end %>

app/views/profiles/return.js.erb
(<%= @str %>)

app/views/profiles/show.html.erb
<h2><%= @profile.name %></h2>
<h5><strong>Bio:</strong> <%= @profile.description %> </h5>

<% if current_user != @profile.user %>
	<% if !current_user.followees.to_a.include?(@profile.user)  %>
        <% @user = current_user %>
        <% @fu = "f" %>
        <%= render "follows/follow" %>
     <% else %>
        <% @user = current_user %>
        <% @fu = "u" %>
        <%= render "follows/follow" %>
       <%# link_to "unfollow", profile_follow_path(@profile, Follow.where(followee_id: current_user.id, follower_id: @profile.user.id).first), method: :delete %>
       
    <% end %>
<% end %>

<h4><%= @profile.name %>'s tweets:</h4>
<ul>
<%= render @tweets %>
</ul>