config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  
  devise_for :users , controllers: {
        registrations: 'users/registrations', 
        omniauth_callbacks: "users/omniauth_callbacks"

      }
  resources :profiles do
     resources :tweets
  end

  get '/feed' => 'feed#userfeed'
  root 'feed#userfeed'

  post "/follow/:profile_id/f" => "follows#create"
  post "/follow/:profile_id/u" => "follows#destroy"

  get "/search/:phrase" => "profiles#search"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  include SimpleHashtag::Hashtaggable
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	def new
		@user = current_user
		@tweet = Tweet.new
	end

	def create
		paramsToSave = tweet_params
		paramsToSave[:user] = current_user
		@tweet = Tweet.new(paramsToSave)
		if @tweet.save
			redirect_to feed_path
		else
			render "new"
		end


	end

	def edit
		@user = current_user
		@tweet = Tweet.find(params[:id])
	end

	def update
		@tweet = Tweet.find(params[:id])
		@tweet.update(tweet_params)
		if @tweet.valid?
			redirect_to feed_path
		else
			render "edit"
		end
	end

	def destroy
		@tweet = Tweet.find(params[:id])
		@tweet.destroy
		redirect_to feed_path #correct this to be dynamic
	end



	private
	def tweet_params
		params.require(:tweet).permit(:body)
	end
end

app/helpers/tweets_helper.rb
module TweetsHelper
	 

end

app/views/tweets/_form.html.erb
<%= form_for [@user.profile, @tweet] do |f| %>

<%= f.label :body %>(Enter a tweet)<br>
<%= f.text_area :body, value: @tweet.body, id: "listen" %><br>

<%= f.submit @message%>

<div id = "big">

</div>

<% end %>

<script>
var str1 = "";
var user =  "";
var track = "";
var foundAt = false;
$( "#listen" ).keypress(function() {
  str1 = String.fromCharCode(event.charCode);
  console.log(user);
  if (track == "")
  {
  	foundAt = false;
  	user = "";
  }
  if (str1 == "@")
  {
  	foundAt = true;
  	user = "";
  	track = "@";
  }
  if (foundAt&&str1!="@")
  {
    user +=String.fromCharCode(event.charCode);
    track +=String.fromCharCode(event.charCode);
    loadXMLDoc()
  }
  //console.log(user);
  
});

$( "#listen" ).keyup(function() {
if (event.keyCode==8)
  {
  	user = user.slice(0, user.length-1)
  	if (user.length>0)
  	{
  	loadXMLDoc()
    }
    else
    {
    	track = ""
    	var bigDiv=document.getElementById("big");
    	bigDiv.innerHTML = ""
    }

  }
  console.log(user)

	});

function loadXMLDoc()
{
var xmlhttp;
if (window.XMLHttpRequest)
  {// code for IE7+, Firefox, Chrome, Opera, Safari
  xmlhttp=new XMLHttpRequest();
  }
else
  {// code for IE6, IE5
  xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
xmlhttp.onreadystatechange=function()
  {
  if (xmlhttp.readyState==4 && xmlhttp.status==200)
    {
    	var bigDiv=document.getElementById("big");
    bigDiv.innerHTML = ""
    var div=document.createElement('div');
    
    div.appendChild(document.createTextNode("You could/must be typing\n"));
    div.appendChild(document.createTextNode(xmlhttp.responseText));

    bigDiv.appendChild(div);

    }
  }
xmlhttp.open("GET","http://localhost:3000/search/"+user,true);
xmlhttp.send();
}
</script>

app/views/tweets/_tweet.html.erb
<li>
<%= link_to tweet.user.profile.name, profile_path(tweet.user.profile) %>: 
<%= auto_link_usernames(linkify_hashtags(tweet.body)) %>
<% if tweet.user == current_user %>
     <%= link_to "edit", edit_profile_tweet_path(current_user.profile, tweet) %>
     <%= link_to "delete", profile_tweet_path(current_user.profile, tweet), method: :delete %>
<% end %>

<br><br>
</li>

app/views/tweets/edit.html.erb
<h1>Edit tweet</h1>
<% @message = "edit tweet" %>
<%= render "form" %>

app/views/tweets/new.html.erb
<h1>new tweet</h1>
<% @message = "create tweet" %>
<%= render "form" %>