config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  
  devise_for :users , controllers: {
        registrations: 'users/registrations', 
        omniauth_callbacks: "users/omniauth_callbacks"

      }
  resources :profiles do
     resources :tweets
  end

  get '/feed' => 'feed#userfeed'
  root 'feed#userfeed'

  post "/follow/:profile_id/f" => "follows#create"
  post "/follow/:profile_id/u" => "follows#destroy"

  get "/search/:phrase" => "profiles#search"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<p>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% if current_user.profile != nil %>
  <p>
	<%= link_to "view my profile", profile_path(current_user.profile) %>
	<%= link_to "view feed", feed_path %>
	<%= link_to "new tweet", new_profile_tweet_path(current_user.profile) %>
	<%= link_to "search users", profiles_path(current_user.profile) %>
  </p>
  <% else %>


  <% end %>

<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>




<%= yield %>

</body>
</html>